[ 
  {type:"big_stone",pos:{x:10,y:6}},
  {type:"fir",pos:{x:20,y:3}},
  {type:"fishing_hut",pos:{x:20,y:10}},
  {type:"townhall",pos:{x:9,y:3}},
  {type:"well",pos:{x:5,y:3}},
  {type:"tower",pos:{x:4,y:7}},
  {type:"man",pos:{x:3,y:0}}
]
